- name: Enable sending TrendMicro DeepSecurity logs to syslog
  syslog_config:
    state: present
    name: "{{ trendmicro_syslog_config_name }}"
    facility: local0
    event_format: leef
    direct: false
    server: "{{ syslog_server }}"
    port: 514
    transport: udp
    description: Syslog Api request from Ansible
